name: Build and Deploy CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # update the Node version to meet your needs
          node-version: 16
          cache: npm
      - name: Build
        run: |
          npm ci
          npm run build
          touch out/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./out
          github_token: ${{ secrets.GITHUB_TOKEN }}